baseURL = "http://example.com/"
languageCode = "en-us"
title = "Metaética"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Shane Mulligan"
    description = "Moral judgment for the age of AI"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:mullikine@gmail.com"
    name = "Shane Mulligan"
    weight = 1

[[menu.icon]]
    url = "https://github.com/metaetica/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/mullikine/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/shane-mulligan-811b942b/"
    name = "fab fa-linkedin"
    weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "fab fa-stack-overflow"
#     weight = 5
