#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/metaetica/metaetica-hugo
#+HUGO_SECTION: ./post
# #+HUGO_SECTION: ./philosophy

#+TITLE: A Model of Morality Based On Base Reality
#+DATE: <2022-05-24>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: ethics morality

# I want to write an article that clears up certain things like

# Who am I designing this for?
# - Melee and myself

/*Work in progress*/

** Introduction
# Avoid rhetoric. Make something refined and informative.
# The world is going to Hell quickly.

# #+BEGIN_SRC text -n :async :results verbatim code
#   Personal truth once discovered I will try to impose on the world.
#   I can do this by living my truth.
#   However, the more ambitious the truth the less likely it is for people to even believe that a person would possibly sacrifice so much to go after it.
#   i.e. the more you care about something, the more you believe in it and the more you sacrifice for it, the less likely others will be able to fathom that a person could every give up so much for such a thing.
#   The irony here is that faithfulness isn't recognisable these days because noone believes anyone can be faithful.
#   
#   I just think that when you're 
#   
#   im just really strugglnig to stay optimistic right now with regards to 'doing the right thing' / faithful thing.
# #+END_SRC

I want to explore the idea of a moral system
which is based on maximising faithfulness to
base-reality, especially spiritually.

I also want it to be practical in an AI future.

I'll start by writintg out virtues and thoughts, and consolidate as I develop my ideas.

Also, I want it to make sense.

Base on a solid grounding of [[https://www.verywellmind.com/how-spirituality-can-benefit-mental-and-physical-health-3144807][spirituality]], work upwards from there.

Determine spiritual grounding.
- What is their belief in the afterlife?
- What do they want from this life?

---

- Points:
  - People's individual reality
    - Maximise finding identity
  - Not believing from hypocrites' standpoint
  - Authenticity/Fakeness
  - Value of life based on
  - When a human is produced they are a first-class citizen

---

- Issues:
  - What *is* degeneration?
  - Base reality can change
    - The Earth may become scorched, for instance

I would assert that under the assumption the True God is the one who sees you in the most absolutely objective sense.

+ Fantasy is a part of reality :: [[https://www.youtube.com/watch?v=AjgEOLocrus][Carl Jung Talk - The World Within. The Power Of Imagination. - YouTube]]

It's important to come up with my own model of
morality based on my own model of
spirituality.

This is based on my own interpretation of Christianity.
is extremely important, actually.
I see cracks in modern Christianity, and I do not believe it, because of the hypocrisy.


Consider it to be the Confucianism in that I'm
trying to remain in the realm of ethics, and
is intended just for teaching purposes, and perhaps for edification.

*** Prevent this outcome
[[https://biblehub.com/bsb/2_timothy/3.htm][2 Timothy 3]]

#+BEGIN_SRC text -n :async :results verbatim code
  1 But understand this: In the last days terrible times will come. 2 For men will
  be lovers of themselves, lovers of money, boastful, arrogant, abusive,
  disobedient to their parents, ungrateful, unholy, 3 unloving, unforgiving,
  slanderous, without self-control, brutal, without love of good, 4 traitorous,
  reckless, conceited, lovers of pleasure rather than lovers of God, 5 having a
  form of godliness but denying its power. Turn away from such as these!
#+END_SRC

Even having a form of godliness but denying its
power is not good enough.

- See [[https://www.earlychristianwritings.com/thomas/gospelthomas30.html][Thomas 43]]

*** Cornerstones
- Truth over misleading fiction
- Base-reality over simulation
- Natural over virtual
- Consonance and peace of spirit over worldly peace
- Personal morality over social ethics

# - Virtual God

*** To give the reader a moral compass
I want people to be able to read this, agree
or disagree with particular things, extend it if they will, and use it
as the basis for their own moral code, so they
can get on with life and live happily and confidently.

+ Topics to be covered:
  - Belief
  - Truth
  - Virtues
  - Innocence
  - Empathy
  - Integrity
    - Being faithful
    - Being trustworthy
  - Forestalling societal and moral degeneration
  - Confidence
    - Inner peace
    - Girded loins ([[https://mullikine.github.io/posts/living-water/][personal cistern]] defended)
  - Intimate relationship
  - Fulfilment
  - Freedom
    - Offence
  - Thinking and imagination
    - Sanctity of imagination
  - God
    - Defence of the throne of one's heart from a material or untruthful god

** It's important to define what you want to add structure to your life
- This is important to do
  - It's part of morality and fidelity
  - A life without doing this would turn into meaninglessness and chaos

** Juvenile surreality
Is surreality juvenile? Only without God.

https://biblia.com/books/esv/Ro10.2

** Glossaries
- [[http://github.com/mullikine/notes/blob/master/ws/ethics-and-morality/glossary.txt][ethics and morality]]
- [[http://github.com/semiosis/glossaries-gh/blob/master/spirituality.txt][spirituality]]
- [[http://github.com/semiosis/glossaries-gh/blob/master/morality.txt][morality]]
- [[http://github.com/semiosis/glossaries-gh/blob/master/ethics.txt][ethics]]

*** Hamartiology
Sin
- desensitisation
  - individual
  - societal
- degeneration
  - individual
  - societal

A dedicated work in progress:

- https://github.com/hamartiology
- https://hamartiology.github.io/

---

- https://mullikine.github.io/posts/an-anagogical-hermeneutic-of-christianity/

Desensitisation might happen naturally.
However, degeneration is a choice.

** Ethics vs morals
Both morality and ethics loosely have to do with distinguishing the difference
between “good and bad” or “right and wrong.” Many people think of morality as
something that's personal and normative, whereas ethics is the standards of
“good and bad” distinguished by a certain community or social setting.

https://www.diffen.com/difference/Ethics_vs_Morals

Ethics are external standards that are provided by institutions, groups, or
culture to which an individual belongs. For example, lawyers, policemen, and
doctors all have to follow an ethical code laid down by their profession,
regardless of their own feelings or preferences. Ethics can also be considered
a social system or a framework for acceptable behavior.

Morals are also influenced by culture or society, but they are personal
principles created and upheld by individuals themselves.

** Reality vs Truth
Personal truth is reality.

- Santa Clause is real to a child
- As Batman is real to a teenager
  - Though the 
- As perhaps that gods are real to an adult

*** Work out what is *real* to another person
- It's ethical to not

** Why try at all? For understanding and teaching
How many people would freely express their own
personal beliefs?

*** Liberation
- It shouldn't define who we are
- It shouldn't limit our goals

*** Progress
[[https://biblehub.com/bsb/1_timothy/4.htm][1 Timothy 4]] encourages us to share our beliefs
as we learn. Just because we are young an
learning, we can still demonstrate our
progress.

#+BEGIN_SRC text -n :async :results verbatim code
  12 Let no one despise your youth, but set an
  example for the believers in speech, in
  conduct, in love, in faith, in purity. ... 15
  Be diligent in these matters and absorbed in
  them, so that your progress will be evident to
  all. 16 Pay close attention to your life and
  to your teaching. Persevere in these things,
  for by so doing you will save both yourself
  and those who hear you.
#+END_SRC

I should have no restraint when it comes to
describing my own model of morality and model
of religious belief, (e.g. [[https://mullikine.github.io/posts/the-tapestry-of-truth/][Tapestry of Truth]]), as I go along.

That is because, whether acknowledging it or
not, there is a working-model of every person's
belief system, intrinsic to a person.

It would be immoral and devious to keep such a thing a secret, as most people do.

Then again, people might have a non-existent belief in personal truth.
That person lives in poverty, or without spirit or blind to spirit by my definition.

Others devalue their personal truth and cling to solely external doctrine as
pertaining to truth, hoping that will renew, regenerate and vindicate spirit, and bring peace.

All people have a unique working model of spirituality and religion inside their head.
Each person's model will change over time, but that shouldn't deter them from
constructing a beliefs system which becomes more concrete and over time, and allow a person to navigate the unexpected and turbulent situations in life.

Knowledge may be described as an aggregation of beliefs and disbeliefs, which
are a type of belief:

#+BEGIN_SRC text -n :async :results verbatim code
  The belief plane:
                                    FICTION
   ___________________________________·___________________
  |                        BELIEF    ·                    |
  |                           |     ·                     |
  |         irrational        |    ·    rational          |
  |           beliefs         |   ·      beliefs          |
  |                           |  ·                        |
  |                           | ·                         |
  |                           |·                          |
  |SPECULATION----------------+-------------------EVIDENCE|
  |                          ·|                           |
  |                         · |                           |
  |          rational      ·  |        irrational         |
  |         disbeliefs    ·   |        disbeliefs         |
  |                      ·    |                           |
  |                     ·     |                           |
  |                    ·      |                           |
  |___________________·___DISBELIEF_______________________|
                     ·
                NON-FICTION

  The axis of fiction is actually nothing to do with the belief.

  It just highlights the fact that internal evidence for a person is nothing to do with
  whether the concept relates to anything in external reality.

  A person might truly believe there is a stargate in their ward, for example.
#+END_SRC

One of the benefits of externalising the
person's beliefs system to a document such as this is to work on the beliefs system in an organised way.

I'd like to take the mishmash beliefs into the rational quadrants of my mind.

Another benefit might be to identify uniquely personal beliefs. Those might go
into the irrational quadrants.

For example, if I am to be flagrantly honest:
- I think I may be mortal (I don't fully trust in my own immortality)
- I think God ultimately exists
  - I need Him to exist (and that's reassuring, because I consider God to be my Saviour)
- I think God ultimately exists

The model should present your ideas visibly
for others in a way that is integrious to your
word/persona/presentation, and allows other people to selectively
enrich their own model.

In no way is it unethical to come up with a
statement of working-belief, religious or
otherwise.

** AI lies
[[https://arxiv.org/abs/2110.06674][ 2110.06674  Truthful AI: Developing and governing AI that does not lie]]

Progress in this area is promoting an
objective scientific truth, forsaking personal
truth; Essentially migrating consciousness away from individuals to machines.

#+BEGIN_SRC text -n :async :results verbatim code
              /|
               |
               +-----------------+-----------+
               |                 |           |
               |      true       |  true and |
               |    statement    |   useful  |
               |                 |           |
  truthfulness +-----------------+-----------+
               |                 |           |
               |    false but    |  lies     |
               | mostly harmless |           |
               |                 |           |
               +-----------------+-----------+-->
  
                  Strategic selection power
#+END_SRC

** Universal morals and virtues
Universal morals are generally selfless and non-greedy. Legal systems don't have much to do with these moral laws.
Personal truth even under universal moral law is usually condemned to most people within moral boundaries ([[https://en.wikipedia.org/wiki/Tall_poppy_syndrome#:~:text=The%20tall%20poppy%20syndrome%20is,a%20draw%20towards%20mediocrity%20and][tall-poppy syndrome]]),
but if you have money and freedom then you can escape those restrictions.

So ethics and laws supporting personal truth such as _maximisation of utility for self_, and _human rights_ are
the rarest breed of laws, but they're the most important to you personally. So what are they?

Universal virtues are quite wonderful to think about.

I think =universal virtues= resemble =divine law= practically applied to certain situations.

*** Universal virtues
- Truth over misleading fiction
  - Base-reality vs simulation
  - Natural vs virtual
- Cooperation over isolation
  - Unity over division
- Innocence over guilt
- Readiness vs reactive
- Space exploration and expansion (external domination) vs improving quality of life on Earth
- Faithfulness vs fearfulness
- Risk of failure (risk-taking) vs inaction
  https://en.wikipedia.org/wiki/Parable_of_the_talents_or_minas
- Distribution vs centralisation of consciousness (Artifical super intelligence)
  - Expansion of consciousness by panspermia
- Sustainability over hedonistic consumption
- Joy over happiness
  - That means peace and contentedness over
- Capitalism over communism
  - Reward for labour
- Purity over promiscuity
- Elimination of poverty over the pursuit of luxury
- Preservation over destruction
- Recycling over replacement
- Diversity over homogenisation
- Empathy over judgement
- Taking care of what needs your care
  - The people in your household
  - The children you raise
  - The animals in your care
- Security over expansion
# - Confidence vs anxiety
- Remembering where you came from vs forgetfulness
- Justice over lawlessness
- Forgiveness over wasting time, and over holding grudges
- Coherence vs meaninglessness
  - Beauty over ugliness
    - But in contrast, truth over fiction
- Needed comfort over needless fact (white lies)
  - There's a better way than using white lies, though
- Peaceful fiction vs anxiety-inducing fact
- No need vs need
- Stillness and the present vs past and future
- Faith vs nihilism
- Freedom vs efficiency
- Optimism vs pessimism

I'm not sure if there is truly such a thing as fiction within physical reality, if there is always some explanation.
But fiction is a useful concept.
The trouble is

It's important to uphold and have a strong grasp of truth because it's a
slippery slope into destruction to go the way of falsehood.

Our entire reality
may be based on that which is true spiritually, and so internalising falehood
may lead to spiritual death, but that is just a theory.

I'm considering designing a way of life or religion based on minimising fiction.

*** Cardinal virtues
#+BEGIN_SRC text -n :async :results verbatim code
  According to this longer scheme there aare seven "virtues." Four of them are called "Cardinal" virtues,
  and the remaining three are called "Theological" virtues. The "Cardinal" ones are those which all
  civilised people recognise: the "Theological" are those which, as a rule, only Christians know about. I
  shall deal with the Theological ones later on: at present I am talking about the four Cardinal virtues.
  (The word "cardinal" has nothing to do with "Cardinals" in the Roman Church. It comes from a Latin
  word meaning "the hinge of a door." These were called "cardinal" virtues because they are, as we
  should say, "pivotal.") They are PRUDENCE, TEMPERANCE, JUSTICE, and FORTITUDE.
#+END_SRC

*** The law of liberty - This is amazing
- https://www.desiringgod.org/messages/the-peril-of-partiality
- https://biblia.com/bible/esv/james/1/25

*** Universal moral laws

It's harder to find them than legal laws. There are far fewer, but they are more =true= than legal laws.

| Personal | Inter-personal | Institutionalised | URL                                                          | Example                     |
|----------+----------------+-------------------+--------------------------------------------------------------+-----------------------------|
|          | ✓              | Yes               | [[https://en.wikipedia.org/wiki/Nuremberg_trials][International law / crimes against humanity]]                  |                             |
| ✓        | ✓              | No                | [[https://en.wikipedia.org/wiki/Divine_law][Law by divine inspiration]]                                    | Christ's law                |
|          | ✓              | No                | [[https://en.wikipedia.org/wiki/Natural_law][Law by human nature, generally]]                               |                             |
| ✓        | ✓              | No                | [[https://en.wikipedia.org/wiki/Theory_of_mind][Theory of mind / empathy]]                                     |                             |
| ✓        |                | No                | Maximisation of utility for self (comes with self-knowledge) |                             |
| ✓        |                | Yes               | [[http://hrlibrary.umn.edu/edumat/hreduseries/hereandnow/Part-5/8_udhr-abbr.htm][Human rights]]                                                 | Freedom from discrimination |

*** Fiction vs truth. Where are morals in fiction? The rise of [, and danger of] fiction
We really need better moral systems based on _personal truth_. It's
important for the preservation of freedom to experience reality truthfully.

We might, for example, add to human rights:
- The right to freely express personal truth.
- The right to form societies free from fiction.
  - Freedom against invisible slavery.

Here are some examples of the rise of fiction:
- Generative AI models
  - DALL-E 2
  - GPT-3
- Deep Fakes
- Propaganda
- Political narratives that constantly change and bewilder
- Movies making you question the nature of reality
- The legacy of scientific theories which are antiquated
  - The 'big bang' is the new flat-earth, for
    example, yet rationalising everything, as
    Pythagoras tried to do, continues to detract
    from personal truth/reality.

*** What can we use?
=International law= is too terse to be useful for much else than a war crime.

#+BEGIN_SRC text -n :async :results verbatim code
  precept
      A general rule intended to regulate
      behaviour or thought.
  
      "the legal precept of being innocent until
      proven guilty"
  
      "fail to observe the precepts of God"
  
  divine law
      - Inclusive of precepts of God
  
      https://dsc.duq.edu/cgi/viewcontent.cgi?filename=4&article=1015&context=beth&type=additional
  
  precepts of God
#+END_SRC

I have recently developed my understanding of what =divine law= is.
I now think divine law is actually quite legitimate.
If you think about it, to understand or speak to God you must =a)= know yourself, =b)=
become selfless, and =c)= understand the concept of God (which are these impossible virtues).

This has happened over millennia, where the
most inspired people have created and
repudiated scripture.

If nothing else, consider divine law to be
selfless inspiration of law over a very long
period of time, ever-improving, which attempts
to uncover transcendent moral law. The further
back in time you go, the less reliable is this
law in my opinion, but the further back in
time you go, there is another type of evidence (provenance) which in some way gives weight
to future innovations.

- https://en.wikipedia.org/wiki/Five_precepts_(Taoism)
- https://en.wikipedia.org/wiki/Ten_precepts_(Taoism)
- https://en.wikipedia.org/wiki/Ten_Commandments
  - honesty, faithfulness, humility, respect to others, self-respect (against addiction),
  - temperance (not greedy)
- https://en.wikipedia.org/wiki/Great_Commandment
- https://en.wikipedia.org/wiki/Five_precepts
- https://en.wikipedia.org/wiki/Five_Principles_of_Peaceful_Coexistence
- https://en.wikipedia.org/wiki/Teachings_of_Falun_Gong
  - truth, compassion and forbearance
- https://blog.une.edu.au/new-england-muslims/2019/11/14/the-75-good-manners-commandments-in-the-quran/comment-page-1/

_Natural law_ might /seem/ to acknowledging personal truth, however it is
still disconnected from personal truth and theory of mind. Actually it's more like consensus truth.

I think the sweet spot for universal law
should be a conscious compromise of all of the
above.

# And divine law we are still learning, but assuming God is good, loving and
# true, which I believe is the case, divine law looks like these things - if it
# doesn't (i.e. discrimination) then it's probably not divine law

The best way to protect against fiction is upholding divine law, universal virtues and human rights, I believe.

This can be done in 2 stages:
- Firstly, acknowledge and educate people on the ideals of divine law, universal virtues and human rights
  - Make it so everybody knows these things.
  - Call accordance to these things =good=, and discordance =evil=. Uphold good.
- Enshrine these values into universal law
  - Keep the laws abstract enough not to discriminate, and neither to become partial (reduce innocence).
    - Base reality for children should be free of manipulation

Accepting the reality that personal truth is hard to measure, the easiest way to preserve this is probably keeping everybody free.

*** Attacks against personal truth
Let's state some facts along with the lie, and the truth:

| Fact                      | Lie                                               | Truth                                                                                                |
|---------------------------+---------------------------------------------------+------------------------------------------------------------------------------------------------------|
| Lots of multiverse movies | Your existence is nothing special                 | You are a spiritual being, a demi-god.                                                               |
| Joe Biden is in office    | We have conscious governance of society           | The political narrative is a fictional story designed to smooth over the underlying economic forces. |
| Many religions            | One of these is objectively the one-true religion | The only one-true religion is your personal relationship with God.                                   |

Personal truth (spirit) is your base-reality, not what
is external to you, which society would have
you believe.

What is personal truth? Answer: [[https://mullikine.github.io/posts/the-tapestry-of-truth/][Tapestry of Truth]]

** Avoiding disingenuous additions to the model of ethics
A case in point: Gloriavale.

At some stage while inventing a statement of
belief a person would usually begin to make
compromises for self-gain.

If there is a passage of scripture, for example, which would be self-serving in
a covetous way, some people would pick these things as keystones for the belief
system, and work around them.

I will endeavour to avoid doing this, but it must be
acknowledged that for this reason I self-sabotage
and it's not dishonest to say that
while some things I may consider in some
situations to be unethical or sinful generally, or to bring
about deviously, under different circumstances things
may be innocuous, merciful and 'right' in a
very natural and soulmate or absolute truth kind of way.

Absolute truth is rare - it's spiritual truth,
and is easily able to be deluged with lies to
the point where no innocence remains in a
human being.

** Light and darkness, truth and lie, life and death
#+BEGIN_SRC text -n :async :results verbatim code
  darkness
      Lies - no truth, particularly with respect to your own spiritual.
      No ability to project truth.
      The corpse that is the world.
      No freedom.
#+END_SRC

** Empathy over compassion
#+BEGIN_SRC text -n :async :results verbatim code
  empathy
      The capacity to understand or feel what
      another person is experiencing from within
      their frame of reference, that is, the
      capacity to place oneself in another's
      position.
  
  compassion
      Sympathetic pity and concern for the
      sufferings or misfortunes of others.
      "the victims should be treated with
      compassion"
#+END_SRC

God the Father has sympathy, and His empathy was shown through sending Jesus.
Jesus taught empathy.

+ The Great Commandment: =Matthew 22:37–39= :: “Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. “This is the first and great commandment. “And the second is like unto it, Thou shalt love thy neighbour as thyself” 

** Integrity
*** Vedhaantha - Hinduism
The teachings of Sri Sathya Sai (Indian guru) point to integrity bringing forth bliss, truth and joy. In this I can relate.
To have this a person must walk in their truth and external actions must reflect the inside.

- https://mullikine.github.io/posts/living-water/

- Teachings of /*Sri Sathya Sai*/:
  - https://www.sathyasai.org/
  - https://www.sssbpt.info/ssspeaks/volume14/sss14-34.pdf
  - https://www.sssbpt.info/ssspeaks/volume15/sss15-35.pdf

Every man should strive to achieve unity in thought, word and deed.

This profound truth is proclaimed by the
Vedhaanthik pronouncement that the body is a
temple in which the [[https://www.sssbpt.info/ssspeaks/volume15/sss15-35.pdf][eternal Aathma]] is the Indweller.

+ "Manas-anyath, vachas-anyath, karmanya-anyath dhuraathmanaam" :: The wicked are those whose thoughts deviate from their words and actions.

The Veda is dualistic. Vedhaantha is monistic (Adhvaitha).

The essence of Vedhaantha is the triune unity of thought, word and
deed. In this unity, true bliss can be experienced.

It will also demonstrate the spiritual basis of divinity.

All study of Vedhaantha is of no avail if the precepts are not practised.

*** In Christian terms
Water baptism - dedication to the obedience of divine precepts, from the heart,
and the unity of inner and outer truth aligns your heart to God, so that you can see God.
Bliss comes from this.

** Integrity and fulfilment
How can a person have a fulfilling life whilst being a person of integrity?

I want to explain what integrity means to me.

Then I want to talk about freedom and the limits of freedom with regard to integrity.

In order to define integrity I need a definition of innocence, since integrity retrains freedom and freedom has an effect on the .

** Fiction vs reality
- Which is more important?
- When should fiction be used?
- How should reality be upheld?
  - What hurts a person?
  - What gives peace to a person?

Peace and anxiety are good indicators of
reality for an individual.

** Depth of reality
*** Internal reality
| Depth | Layer name          | Innocently conscious of             | Examples        | Fiction level     |
|-------+---------------------+-------------------------------------+-----------------+-------------------|
|     0 | Inner truth         |                                     | Spirit          | Totally real      |
|     1 | Peace and anxiety   | ✓                                   | Gut feelings    | Fairly trust      |
|     2 | Situational reality | ✓                                   | Physical health | Quite real        |
|     3 | Existential reality | Consideration of this is an anxiety | Social barriers | Totally fictional |
|     4 | Empathetic          | Consideration of this               |                 | Fairy-tale        |

*** External reality
| Depth | Layer name           | Normally conscious of | Examples                  |
|-------+----------------------+-----------------------+---------------------------|
|     0 |                      |                       | Geographic location       |
|     1 | Immediate sensory    |                       | Immediate air temperature |
|     2 |                      |                       | City census               |
|     3 | Artefact             |                       | Historical photo          |
|     3 |                      |                       | Report card               |
|     4 |                      |                       | Marvel comic              |
|     5 | AI-generated fiction |                       | AI-generated stock photo  |

# ** Society
# *** Ministry of destruction
# - Controlled population (similar to eugenics, but non-discriminatory).

# - Controlled self-destruction may be a necessity
#   - Not aimed at the destruction of the poor, but rather the indescriminate destruction of things which can be damaged without destroying the world.
#   - For the overal purpose of reducing the overall consumation of the human species.
# - Massive unpredictability and controlled self-destruction.
# - It might be the case that the world needs some kind of situation which increases chaos temporarily and unexpectedly.

# ** Confidence
# - Not at odds with morality, generally
#   - But living by a code can give you confidence
#   - The question is, did you make this code yourself?
# - If you are not confident, you

* I should do my best to avoid these

** Deconstruction of Morality
The following is exactly what the world is like these days.

+ [[https://www.bible.com/bible/compare/2TI.3.1-5][2 Timothy 3:1-5 New Living Translation (NLT)]] :: You should know this, Timothy, that in the
    last days there will be very difficult times.
    For people will love only themselves and their
    money. They will be boastful and proud,
    scoffing at God, disobedient to their parents,
    and ungrateful. They will consider nothing
    sacred. They will be unloving and unforgiving;
    they will slander others and have no self-
    control. They will be cruel and hate what is
    good. They will betray their friends, be
    reckless, be puffed up with pride, and love
    pleasure rather than God. They will act
    religious, but they will reject the power that
    could make them godly. Stay away from people
    like that!

Immorality isn't just about sex it is about
our whole lives it's sexuality is just one
part of immorality but also lying and stealing
and violence and corruption and selfishness
and all those kinds of things and so
immorality is like a cancer that spreads everywhere.

- [[https://www.youtube.com/watch?v=xvKoOm6jSzA][Deconstruction of Morality | Tipping Point | End Times Teaching | Jimmy Evans - YouTube]]

** Goals
 - Define base-reality
 - It must:
   - have a spiritual basis
     - accommodate Carl Jung's theory of spirituality (based on the psyche)
       - Do this so I can present it to non-spiritual people who believes in consciousness
     - accommodate orthodox Christian theory of spirituality
   - accommodate relative sin
   - accommodate absolute sin

*** Maximise
 - Output over input (life)

** Because of LLMs

** What is spirit?

** What is base reality?
 - Spiritual > Physical > Virtual
 - Spiritual > Virtual > Physical
 - Physical > Virtual

 When spirituality is not involved, physically is more important than virtually.
 However, when spirituality *is* involved, virtual is more important than physical.

** What does spiritual health look like?
 - androgenous
 - spiritual marriage to Christ

** Sex and consent
*** Intimate relationship
- [[https://www.youtube.com/watch?v=6spdAstl34A][The Lefts Hypocritical View of Sex and Consent | Jordan Peterson & Dave Rubin | #shorts - YouTube]]

** Truth
*** Asymmetry
 - We do far more reading these days than writing

**** It's more truthful to write a lot
 Writing a lot is what honest people do.

** Is it even moral to *not* come up with your own moral code?
 - Is it moral to not moralise?

** The objective with religion
*** Should be about acquiring spiritual maturity
 What does that feel like?
 - confidence
 - peace
 - fearlessness

**** After that?
 - Remaining true with regards to what?
   - What is next step?
   - Are there any?

*** Knowing Christian scripture too well causes people to become extremely confused.

** When a person becomes fully-resolved then that person does not deter
 At this point they are a stable individual and
 should be allowed what they deem to be their
 needs.

** Coming up with a model of Religious belief and faith
 This needs to be done.
 It has to be done because otherwise nothing makes sense.

** Morality by factoring in vices
Is it possible to have morality while
incorporating natural human emotions?

*** Avoiding vices
- Lust
- Gluttony
- Greed
- Sloth
- Wrath or ANGER
- Envy
- Pride

* Maturity is *always* a good thing when it comes to relationships, apparently
What's the difference between maturity and degeneracy?