#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/metaetica/metaetica-hugo
#+HUGO_SECTION: ./post

#+TITLE: Review of '[2110.06674] Truthful AI: Developing and governing AI that does not lie'
#+DATE: <2021-10-15>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: alethiology epistemology

** Summary
This is my notebook as I go through this paper.

+ Original article :: [[https://arxiv.org/abs/2110.06674][ 2110.06674  Truthful AI: Developing and governing AI that does not lie]]

+ Truth :: https://en.wikipedia.org/wiki/Truth

I have not yet read the paper, but this page will serve as my notes for it.

** Glossaries
- [[http://github.com/semiosis/glossaries-gh/blob/master/ai-alethiology.txt][AI Alethiology]]
- [[http://github.com/semiosis/glossaries-gh/blob/master/alethiology.txt][Alethiology]]
- [[http://github.com/semiosis/glossaries-gh/blob/master/epistemology.txt][Epistemology]]

** Initial thoughts
An institution, even a benevolent one, reminds
me of The Ministry of Truth from 1984. An
institution is better than anarchy, in my
opinion, but I still think that decentralised
governance, such as from a blockchain is a
better algorithm. Perhaps the Future of Life
Institute could create such a benevolent
blockchain for the dissemination of power over
what is true.

** Benefits of truthful AI
- people who believe AI-produced statements will avoid being deceived. This could avert some of the most concerning possible AI-facilitated catastrophes.
- enables justified trust in AI-produced statements (if people cannot reliably distinguish truths and falsehoods, disbelieving falsehoods will also mean disbelieving truths).

** Truthfulness standards
- Domain specific truthfulness standards

There are a few different dimensions on which standards can vary:
- A standard can be higher or lower. A high standard is more demanding and requires a greater minimum level of truthfulness.
- A standard can be more or less widely adhered to, within the domain where it applies.
- Failure to comply with a standard can result in different kinds of sanctions, either formal (e.g. specified in law) or informal (e.g. as a result of social norms).

** Types of truth
This is a work-in-progress.

| Types          | Mentioned   | Other Possible candidates              |
|----------------+-------------+----------------------------------------|
| Correspondence |             |                                        |
| Coherence      |             | Language model                         |
| Pragmatic      |             | Interrogating language model           |
| Constructivist | Institution | Blockchain for training data accretion |
| Consensus      |             | Blockchain for trained models          |
| Deflationary   |             |                                        |
| Performative   |             |                                        |

*** No mention of blockchain
Here are my previous notes on base-truth via language models on the blockchain.

- https://mullikine.github.io/posts/language-models-as-truth/